/**
 * Skin registry — self-written palettes that restyle the dsh web UI through
 * its semantic color tokens (`--dsw-alias-*`). Each skin ships a light and a
 * dark palette; dsh's own mode marker (`body[data-ds-dark-theme]`) decides
 * which block is active, so skins stay coherent with the user's light/dark
 * setting instead of fighting it.
 *
 * The `default` skin is not an entry: it means "no override" and removes the
 * injected stylesheet entirely.
 */

/** One semantic token override (alias token name without the leading `--dsw-alias-`). */
export interface Palette {
  [token: string]: string
}

/** A selectable skin. */
export interface DshSkin {
  id: string
  name: string
  description: string
  /** `--dsw-alias-*` overrides (the main semantic tokens). */
  light: Palette
  dark: Palette
  /**
   * `--dsw-specific-*` overrides — surfaces the alias tokens do not drive
   * (sidebar surface, sidebar nav item states, floating menus). Kept
   * separate so alias keys stay short and the specific set is explicit.
   */
  specific: { light: Palette; dark: Palette }
}

/** Serialize one selector block: alias tokens plus optional specific tokens. */
function block(selector: string, palette: Palette, specific?: Palette): string {
  const aliasBody = Object.entries(palette)
    .map(([token, value]) => `--dsw-alias-${token}:${value};`)
    .join('')
  const specificBody = specific === undefined ? '' : Object.entries(specific)
    .map(([token, value]) => `--dsw-specific-${token}:${value};`)
    .join('')
  return `${selector}{${aliasBody}${specificBody}}`
}

function buildCss(skin: DshSkin): string {
  // The web UI declares its alias tokens on `body` (light) and
  // `body[data-ds-dark-theme]` (dark). Overriding on `:root` would lose the
  // cascade (body wins for its own subtree), so both blocks must target the
  // same selectors the app uses; the injected stylesheet is appended to head
  // and therefore wins at equal specificity.
  return `${block('body', skin.light, skin.specific.light)}${block('body[data-ds-dark-theme]', skin.dark, skin.specific.dark)}`
}

/**
 * The built-in skins. Palettes are original compositions over the dsw alias
 * token set; adjust freely.
 */
export const SKINS: DshSkin[] = [
  {
    id: 'midnight',
    name: '午夜蓝',
    description: '深海蓝调，冷静专注',
    light: {
      'bg-base': '#eef1f8',
      'bg-layer-1': '#e4e9f4',
      'bg-layer-2': '#dbe2f0',
      'bg-layer-3': '#d3dcec',
      'bg-overlay': '#f4f7fd',
      'label-primary': '#1c2333',
      'label-secondary': '#3f4a63',
      'label-tertiary': '#5b6884',
      'label-dimmed': '#7c8aa8',
      'border-l1': '#d5dceb',
      'border-l2': '#c4cfe2',
      'border-l3': '#b3c0d8',
      'brand-primary': '#3b6fe0',
      'brand-primary-invert': '#ffffff',
      'brand-text': '#ffffff',
      'button-primary-fill': '#3b6fe0',
      'button-primary-hover': '#2f5cc4',
      'button-primary-dimmed': '#dbe4fa',
      'interactive-bg-hover': '#dce4f2',
      'interactive-bg-active': '#cfd9ec',
      'markdown-code-block': '#e2e8f4',
      'markdown-inline-code': '#dde5f2',
      'scrollbar-bg-l1': '#d5dceb',
      'scrollbar-hover-l1': '#c0cbe0',
      'bg-module-platform': '#d3dcec',
      'tooltip-bg': '#1c2333',
      'toast-bg': '#1c2333',
    },
    dark: {
      'bg-base': '#0a1222',
      'bg-layer-1': '#0f1a30',
      'bg-layer-2': '#14223c',
      'bg-layer-3': '#192a48',
      'bg-overlay': '#0c1528',
      'label-primary': '#dbe6ff',
      'label-secondary': '#9fb3d9',
      'label-tertiary': '#7f93bb',
      'label-dimmed': '#617297',
      'border-l1': '#1c2b4a',
      'border-l2': '#24365a',
      'border-l3': '#2d4169',
      'brand-primary': '#5b8cff',
      'brand-primary-invert': '#0a1222',
      'brand-text': '#0a1222',
      'button-primary-fill': '#3b6fe0',
      'button-primary-hover': '#4c7ceb',
      'button-primary-dimmed': '#1d3050',
      'interactive-bg-hover': '#182742',
      'interactive-bg-active': '#1f3150',
      'markdown-code-block': '#0d1830',
      'markdown-inline-code': '#14223c',
      'scrollbar-bg-l1': '#1c2b4a',
      'scrollbar-hover-l1': '#2b4068',
      'tooltip-bg': '#1c2333',
      'toast-bg': '#1c2333',
      'bg-module-platform': '#192a48',
    },
    specific: {
      light: {
        'sidebar-fill': '#e4e9f4',
        'sidebar-nav-item-active-accent': '#3b6fe0',
        'sidebar-nav-item-active': '#dbe4fa',
        'sidebar-nav-item-hover': '#dce4f2',
        menu: '#d3dcec',
        bubble: '#e8edf8',
        'bubble-highlight': '#dbe4fa',
      },
      dark: {
        'sidebar-fill': '#0f1a30',
        'sidebar-nav-item-active-accent': '#5b8cff',
        'sidebar-nav-item-active': '#1d3050',
        'sidebar-nav-item-hover': '#182742',
        menu: '#192a48',
        bubble: '#14223c',
        'bubble-highlight': '#1d3050',
      },
    },
  },
  {
    id: 'paper',
    name: '旧纸张',
    description: '暖黄米色，护眼复古',
    light: {
      'bg-base': '#f4eee1',
      'bg-layer-1': '#ede4d2',
      'bg-layer-2': '#e7dcc6',
      'bg-layer-3': '#e0d3ba',
      'bg-overlay': '#f8f2e7',
      'label-primary': '#3d3527',
      'label-secondary': '#5c513d',
      'label-tertiary': '#7a6d54',
      'label-dimmed': '#98896c',
      'border-l1': '#d9cbaa',
      'border-l2': '#cdbb94',
      'border-l3': '#c0ab7f',
      'brand-primary': '#7a5c2e',
      'brand-primary-invert': '#f8f2e7',
      'brand-text': '#f8f2e7',
      'button-primary-fill': '#7a5c2e',
      'button-primary-hover': '#664c26',
      'button-primary-dimmed': '#e9dfc8',
      'interactive-bg-hover': '#e8ddc6',
      'interactive-bg-active': '#e0d3b8',
      'markdown-code-block': '#e9dfc8',
      'markdown-inline-code': '#e6dac0',
      'scrollbar-bg-l1': '#d9cbaa',
      'scrollbar-hover-l1': '#c8b688',
      'bg-module-platform': '#e0d3ba',
      'tooltip-bg': '#3d3527',
      'toast-bg': '#3d3527',
    },
    dark: {
      'bg-base': '#211d15',
      'bg-layer-1': '#2a2419',
      'bg-layer-2': '#332b1d',
      'bg-layer-3': '#3c3222',
      'bg-overlay': '#252016',
      'label-primary': '#e8dcc0',
      'label-secondary': '#b3a483',
      'label-tertiary': '#93855f',
      'label-dimmed': '#75684a',
      'border-l1': '#3a3122',
      'border-l2': '#463b29',
      'border-l3': '#524430',
      'brand-primary': '#c9a45c',
      'brand-primary-invert': '#211d15',
      'brand-text': '#211d15',
      'button-primary-fill': '#8a6a33',
      'button-primary-hover': '#9d7a3e',
      'button-primary-dimmed': '#37301f',
      'interactive-bg-hover': '#322a1c',
      'interactive-bg-active': '#3a3120',
      'markdown-code-block': '#262015',
      'markdown-inline-code': '#2e281b',
      'scrollbar-bg-l1': '#3a3122',
      'scrollbar-hover-l1': '#4a3f2b',
      'tooltip-bg': '#3d3527',
      'toast-bg': '#3d3527',
      'bg-module-platform': '#3c3222',
    },
    specific: {
      light: {
        'sidebar-fill': '#ede4d2',
        'sidebar-nav-item-active-accent': '#7a5c2e',
        'sidebar-nav-item-active': '#e9dfc8',
        'sidebar-nav-item-hover': '#e8ddc6',
        menu: '#e0d3ba',
        bubble: '#f0e9d8',
        'bubble-highlight': '#e9dfc8',
      },
      dark: {
        'sidebar-fill': '#2a2419',
        'sidebar-nav-item-active-accent': '#c9a45c',
        'sidebar-nav-item-active': '#37301f',
        'sidebar-nav-item-hover': '#322a1c',
        menu: '#3c3222',
        bubble: '#332b1d',
        'bubble-highlight': '#37301f',
      },
    },
  },
  {
    id: 'terminal',
    name: '终端绿',
    description: '磷光绿，命令行质感',
    light: {
      'bg-base': '#eef5ec',
      'bg-layer-1': '#e2efe0',
      'bg-layer-2': '#d7e9d4',
      'bg-layer-3': '#cce3c9',
      'bg-overlay': '#f2f8f0',
      'label-primary': '#1d301c',
      'label-secondary': '#3a5436',
      'label-tertiary': '#55774f',
      'label-dimmed': '#74996d',
      'border-l1': '#cfe3cc',
      'border-l2': '#bfd8bb',
      'border-l3': '#aecda9',
      'brand-primary': '#2e7d32',
      'brand-primary-invert': '#f2f8f0',
      'brand-text': '#f2f8f0',
      'button-primary-fill': '#2e7d32',
      'button-primary-hover': '#266a2a',
      'button-primary-dimmed': '#d8ecd5',
      'interactive-bg-hover': '#dcebda',
      'interactive-bg-active': '#d0e4ce',
      'markdown-code-block': '#dfeede',
      'markdown-inline-code': '#d8ead6',
      'scrollbar-bg-l1': '#cfe3cc',
      'scrollbar-hover-l1': '#b9d6b4',
      'bg-module-platform': '#cce3c9',
      'tooltip-bg': '#1d301c',
      'toast-bg': '#1d301c',
    },
    dark: {
      'bg-base': '#0a130b',
      'bg-layer-1': '#0e1c10',
      'bg-layer-2': '#132614',
      'bg-layer-3': '#17301a',
      'bg-overlay': '#0b150d',
      'label-primary': '#a9f0a9',
      'label-secondary': '#6fae6f',
      'label-tertiary': '#558d55',
      'label-dimmed': '#3f6e3f',
      'border-l1': '#1c3a20',
      'border-l2': '#244928',
      'border-l3': '#2c5831',
      'brand-primary': '#33ff88',
      'brand-primary-invert': '#0a130b',
      'brand-text': '#0a130b',
      'button-primary-fill': '#1f6e3a',
      'button-primary-hover': '#278346',
      'button-primary-dimmed': '#14301c',
      'interactive-bg-hover': '#11241a',
      'interactive-bg-active': '#162b1e',
      'markdown-code-block': '#0c180e',
      'markdown-inline-code': '#102215',
      'scrollbar-bg-l1': '#1c3a20',
      'scrollbar-hover-l1': '#2a5230',
      'tooltip-bg': '#0e1c10',
      'toast-bg': '#0e1c10',
      'bg-module-platform': '#17301a',
    },
    specific: {
      light: {
        'sidebar-fill': '#e2efe0',
        'sidebar-nav-item-active-accent': '#2e7d32',
        'sidebar-nav-item-active': '#d8ecd5',
        'sidebar-nav-item-hover': '#dcebda',
        menu: '#cce3c9',
        bubble: '#e8f3e6',
        'bubble-highlight': '#d8ecd5',
      },
      dark: {
        'sidebar-fill': '#0e1c10',
        'sidebar-nav-item-active-accent': '#33ff88',
        'sidebar-nav-item-active': '#14301c',
        'sidebar-nav-item-hover': '#11241a',
        menu: '#17301a',
        bubble: '#132614',
        'bubble-highlight': '#14301c',
      },
    },
  },
  {
    id: 'zcode',
    name: 'ZCode',
    description: '智谱 ZCode IDE 实测色板（浅色/深色）',
    light: {
      // ZCode 浅色实测：内容 #ffffff → 面板 #ececee → 标题/状态栏 #f8f8f8
      'bg-base': '#ffffff',
      'bg-layer-1': '#ececee',
      'bg-layer-2': '#ececee',
      'bg-layer-3': '#f8f8f8',
      'bg-overlay': '#f8f8f8',
      'label-primary': '#262626',
      'label-secondary': '#55565a',
      'label-tertiary': '#8a8a8d',
      'label-dimmed': '#b0b0b2',
      'border-l1': '#e3e3e5',
      'border-l2': '#d9d9db',
      'border-l3': '#c9c9cb',
      'brand-primary': '#0095df',
      'brand-primary-invert': '#ffffff',
      'brand-text': '#ffffff',
      'button-primary-fill': '#0095df',
      'button-primary-hover': '#007fbf',
      'button-primary-dimmed': '#d9edf9',
      'interactive-bg-hover': '#e0e0e2',
      'interactive-bg-active': '#d3d3d5',
      'markdown-code-block': '#f4f4f6',
      'markdown-inline-code': '#ececee',
      'scrollbar-bg-l1': '#c8c8ca99',
      'scrollbar-hover-l1': '#a8a8aa',
      'bg-module-platform': '#f8f8f8',
      'tooltip-bg': '#262626',
      'toast-bg': '#262626',
      'state-success-primary': '#2da44e',
      'state-error-primary': '#cf222e',
      'state-warn-primary': '#bf8700',
      'state-business-primary': '#0095df',
    },
    dark: {
      // ZCode 深色实测：标题/状态栏 #161616（比内容更暗）→ 面板/侧栏/编辑器 #2b2b2b → 浮层 #363636
      'bg-base': '#2b2b2b',
      'bg-layer-1': '#2b2b2b',
      'bg-layer-2': '#363636',
      'bg-layer-3': '#161616',
      'bg-overlay': '#1f1f1f',
      'label-primary': '#dcdcdc',
      'label-secondary': '#a0a0a0',
      'label-tertiary': '#888888',
      'label-dimmed': '#6b6b6b',
      'border-l1': '#3c3c3c',
      'border-l2': '#545454',
      'border-l3': '#626262',
      'brand-primary': '#0096e0',
      'brand-primary-invert': '#161616',
      'brand-text': '#161616',
      'button-primary-fill': '#0096e0',
      'button-primary-hover': '#1ba5e8',
      'button-primary-dimmed': '#1d3a47',
      'interactive-bg-hover': '#3a3a3a',
      'interactive-bg-active': '#414141',
      'markdown-code-block': '#232323',
      'markdown-inline-code': '#363636',
      'scrollbar-bg-l1': '#54545499',
      'scrollbar-hover-l1': '#6e6e6e',
      'tooltip-bg': '#161616',
      'toast-bg': '#161616',
      'state-success-primary': '#3fb950',
      'state-error-primary': '#f85149',
      'state-warn-primary': '#d29922',
      'state-business-primary': '#0096e0',
      'bg-module-platform': '#161616',
    },
    specific: {
      light: {
        'sidebar-fill': '#ececee',
        'sidebar-nav-item-active-accent': '#0095df',
        'sidebar-nav-item-active': '#d9edf9',
        'sidebar-nav-item-hover': '#e0e0e2',
        menu: '#f8f8f8',
        bubble: '#f4f4f6',
        'bubble-highlight': '#d9edf9',
      },
      dark: {
        // ZCode 深色实测：侧栏 #363636（比内容 #2b2b2b 亮一步），标题栏 #161616 更暗
        'sidebar-fill': '#363636',
        'sidebar-nav-item-active-accent': '#0096e0',
        'sidebar-nav-item-active': '#1d3a47',
        'sidebar-nav-item-hover': '#3a3a3a',
        menu: '#161616',
        bubble: '#363636',
        'bubble-highlight': '#1d3a47',
      },
    },
  },
  {
    id: 'aurora',
    name: '极光紫',
    description: '紫罗兰辉光，梦幻渐变',
    light: {
      'bg-base': '#f1eefb',
      'bg-layer-1': '#e8e4f7',
      'bg-layer-2': '#e0daf4',
      'bg-layer-3': '#d8d0f0',
      'bg-overlay': '#f5f2fd',
      'label-primary': '#241f3d',
      'label-secondary': '#453d6b',
      'label-tertiary': '#645a94',
      'label-dimmed': '#8377b8',
      'border-l1': '#d6cdf0',
      'border-l2': '#c7bce8',
      'border-l3': '#b7a9df',
      'brand-primary': '#7c5cff',
      'brand-primary-invert': '#f5f2fd',
      'brand-text': '#f5f2fd',
      'button-primary-fill': '#7c5cff',
      'button-primary-hover': '#6a4ae8',
      'button-primary-dimmed': '#e0d8fb',
      'interactive-bg-hover': '#e6e0f8',
      'interactive-bg-active': '#dcd3f4',
      'markdown-code-block': '#e4def7',
      'markdown-inline-code': '#ded6f4',
      'scrollbar-bg-l1': '#d6cdf0',
      'scrollbar-hover-l1': '#c3b6e6',
      'bg-module-platform': '#d8d0f0',
      'tooltip-bg': '#241f3d',
      'toast-bg': '#241f3d',
    },
    dark: {
      'bg-base': '#0e0d1d',
      'bg-layer-1': '#151331',
      'bg-layer-2': '#1c1a40',
      'bg-layer-3': '#24214e',
      'bg-overlay': '#100f21',
      'label-primary': '#e2dcff',
      'label-secondary': '#a79fe0',
      'label-tertiary': '#877dc4',
      'label-dimmed': '#665ca6',
      'border-l1': '#2b2760',
      'border-l2': '#35306f',
      'border-l3': '#3f397e',
      'brand-primary': '#9f7cff',
      'brand-primary-invert': '#0e0d1d',
      'brand-text': '#0e0d1d',
      'button-primary-fill': '#6a45e8',
      'button-primary-hover': '#7a57f0',
      'button-primary-dimmed': '#241f4d',
      'interactive-bg-hover': '#1c1940',
      'interactive-bg-active': '#24214b',
      'markdown-code-block': '#121026',
      'markdown-inline-code': '#191632',
      'scrollbar-bg-l1': '#2b2760',
      'scrollbar-hover-l1': '#3a3480',
      'tooltip-bg': '#151331',
      'toast-bg': '#151331',
      'bg-module-platform': '#24214e',
    },
    specific: {
      light: {
        'sidebar-fill': '#e8e4f7',
        'sidebar-nav-item-active-accent': '#7c5cff',
        'sidebar-nav-item-active': '#e0d8fb',
        'sidebar-nav-item-hover': '#e6e0f8',
        menu: '#d8d0f0',
        bubble: '#ece7fa',
        'bubble-highlight': '#e0d8fb',
      },
      dark: {
        'sidebar-fill': '#151331',
        'sidebar-nav-item-active-accent': '#9f7cff',
        'sidebar-nav-item-active': '#241f4d',
        'sidebar-nav-item-hover': '#1c1940',
        menu: '#24214e',
        bubble: '#1c1a40',
        'bubble-highlight': '#241f4d',
      },
    },
  },
  {
    // Ported from the Reasonix desktop "Noir Gold" official theme
    // (desktop/themes/official/official-noir-gold/theme.json). Literal
    // surfaces/text/accent tokens map 1:1; intermediate tones (layer-2,
    // borders-l2, tertiary labels, button hover/dimmed, interactive washes,
    // bubble surfaces) are derived with a uniform mix/darken rule set,
    // documented in docs/skins/rx-noir-gold.md. Light dimmed nudged darker
    // (#8F8469) so it stays >= 3.5:1 on bg-base.
    id: 'rx-noir-gold',
    name: '黑金（Noir Gold）',
    description: 'Reasonix 官方 Noir Gold——暖纸金与墨黑鎏金',
    light: {
      'bg-base': '#FDFAF2',
      'bg-layer-1': '#F6F0DF',
      'bg-layer-2': '#F7F1E1',
      'bg-layer-3': '#FEFBF4',
      'bg-overlay': '#FEFBF4',
      'label-primary': '#2A241B',
      'label-secondary': '#5C5340',
      'label-tertiary': '#7B715A',
      'label-dimmed': '#8F856C',
      'border-l1': '#EFE8D2',
      'border-l2': '#DFD5B6',
      'border-l3': '#CCBE94',
      'brand-primary': '#7A5A16',
      'brand-primary-invert': '#FCF8EE',
      'brand-text': '#FCF8EE',
      'button-primary-fill': '#6B4F13',
      'button-primary-hover': '#5F4611',
      'button-primary-dimmed': '#EFE8D8',
      'interactive-bg-hover': '#F6F0DE',
      'interactive-bg-active': '#F5EFDE',
      'markdown-code-block': '#FAF5E8',
      'markdown-inline-code': '#F6F0DF',
      'scrollbar-bg-l1': '#E6DEC2',
      'scrollbar-hover-l1': '#CCBE94',
      'bg-module-platform': '#F7F1E1',
      'tooltip-bg': '#2A241B',
      'toast-bg': '#2A241B',
    },
    dark: {
      'bg-base': '#131009',
      'bg-layer-1': '#15120E',
      'bg-layer-2': '#171410',
      'bg-layer-3': '#1D1913',
      'bg-overlay': '#14110D',
      'label-primary': '#F8F1DF',
      'label-secondary': '#D6CBAE',
      'label-tertiary': '#B6AC8E',
      'label-dimmed': '#968C6E',
      'border-l1': '#2A2418',
      'border-l2': '#372E1F',
      'border-l3': '#463B27',
      'brand-primary': '#D9B45B',
      'brand-primary-invert': '#1D1503',
      'brand-text': '#1D1503',
      'button-primary-fill': '#D9B45B',
      'button-primary-hover': '#DEBD6F',
      'button-primary-dimmed': '#3F3213',
      'interactive-bg-hover': '#15120E',
      'interactive-bg-active': '#14110D',
      'markdown-code-block': '#14110C',
      'markdown-inline-code': '#15120E',
      'scrollbar-bg-l1': '#312A1C',
      'scrollbar-hover-l1': '#463B27',
      'bg-module-platform': '#171410',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
        'sidebar-fill': '#F5EFDD',
        'sidebar-nav-item-active-accent': '#7A5A16',
        'sidebar-nav-item-active': '#EFE8D8',
        'sidebar-nav-item-hover': '#F6F0DE',
        menu: '#FEFBF4',
        bubble: '#FAF5E8',
        'bubble-highlight': '#EFE8D8',
      },
      dark: {
        'sidebar-fill': '#14110D',
        'sidebar-nav-item-active-accent': '#D9B45B',
        'sidebar-nav-item-active': '#3F3213',
        'sidebar-nav-item-hover': '#15120E',
        menu: '#1D1913',
        bubble: '#18140E',
        'bubble-highlight': '#392D10',
      },
    },
  },
  {
    id: 'rx-crimson-horizon',
    name: '绯红地平线（Crimson Horizon）',
    description: 'Reasonix 官方 Crimson Horizon——炽红地线，张力十足',
    light: {
      'bg-base': '#FFFBFA',
      'bg-layer-1': '#F9EEEC',
      'bg-layer-2': '#FBF1EF',
      'bg-layer-3': '#FFFFFF',
      'bg-overlay': '#FFFFFF',
      'label-primary': '#301D1D',
      'label-secondary': '#6B4644',
      'label-tertiary': '#8A6360',
      'label-dimmed': '#9D7774',
      'border-l1': '#F6E4E2',
      'border-l2': '#ECCECA',
      'border-l3': '#DFB3AD',
      'brand-primary': '#B92B38',
      'brand-primary-invert': '#FFF8F7',
      'brand-text': '#FFF8F7',
      'button-primary-fill': '#A32631',
      'button-primary-hover': '#90222C',
      'button-primary-dimmed': '#F8E4E4',
      'interactive-bg-hover': '#F9EDEB',
      'interactive-bg-active': '#F9EDEB',
      'markdown-code-block': '#FCF4F3',
      'markdown-inline-code': '#F9EEEC',
      'scrollbar-bg-l1': '#F0D8D5',
      'scrollbar-hover-l1': '#DFB3AD',
      'bg-module-platform': '#FBF1EF',
      'tooltip-bg': '#301D1D',
      'toast-bg': '#301D1D',
    },
    dark: {
      'bg-base': '#201116',
      'bg-layer-1': '#221318',
      'bg-layer-2': '#25141A',
      'bg-layer-3': '#2B181E',
      'bg-overlay': '#14110D',
      'label-primary': '#FFF1F2',
      'label-secondary': '#DFB3B6',
      'label-tertiary': '#C6989D',
      'label-dimmed': '#AC7E84',
      'border-l1': '#361B24',
      'border-l2': '#45242F',
      'border-l3': '#582F3C',
      'brand-primary': '#FF6772',
      'brand-primary-invert': '#2A0E12',
      'brand-text': '#2A0E12',
      'button-primary-fill': '#FF6772',
      'button-primary-hover': '#FF7983',
      'button-primary-dimmed': '#501E23',
      'interactive-bg-hover': '#221318',
      'interactive-bg-active': '#211218',
      'markdown-code-block': '#211217',
      'markdown-inline-code': '#221318',
      'scrollbar-bg-l1': '#3E202A',
      'scrollbar-hover-l1': '#582F3C',
      'bg-module-platform': '#25141A',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#F9ECEA',
      'sidebar-nav-item-active-accent': '#B92B38',
      'sidebar-nav-item-active': '#F8E4E4',
      'sidebar-nav-item-hover': '#F9EDEB',
      'menu': '#FFFFFF',
      'bubble': '#FCF4F3',
      'bubble-highlight': '#F8E4E4',
      },
      dark: {
      'sidebar-fill': '#211218',
      'sidebar-nav-item-active-accent': '#FF6772',
      'sidebar-nav-item-active': '#501E23',
      'sidebar-nav-item-hover': '#221318',
      'menu': '#2B181E',
      'bubble': '#26141A',
      'bubble-highlight': '#4A1B20',
      },
    },
  },
  {
    id: 'rx-cyan-stage',
    name: '青蓝舞台（Cyan Stage）',
    description: 'Reasonix 官方 Cyan Stage——冰川青蓝，冷静清晰',
    light: {
      'bg-base': '#F6FDFE',
      'bg-layer-1': '#E4F5F7',
      'bg-layer-2': '#E8F6F8',
      'bg-layer-3': '#FAFEFE',
      'bg-overlay': '#FAFEFE',
      'label-primary': '#173238',
      'label-secondary': '#43606A',
      'label-tertiary': '#5A7A84',
      'label-dimmed': '#698992',
      'border-l1': '#DAEDF0',
      'border-l2': '#BEE0E5',
      'border-l3': '#9CCFD7',
      'brand-primary': '#007C92',
      'brand-primary-invert': '#F1FCFD',
      'brand-text': '#F1FCFD',
      'button-primary-fill': '#006D80',
      'button-primary-hover': '#006172',
      'button-primary-dimmed': '#D9EFF2',
      'interactive-bg-hover': '#E4F5F7',
      'interactive-bg-active': '#E3F4F6',
      'markdown-code-block': '#EDF9FA',
      'markdown-inline-code': '#E4F5F7',
      'scrollbar-bg-l1': '#CAE6EA',
      'scrollbar-hover-l1': '#9CCFD7',
      'bg-module-platform': '#E8F6F8',
      'tooltip-bg': '#173238',
      'toast-bg': '#173238',
    },
    dark: {
      'bg-base': '#0A2027',
      'bg-layer-1': '#0C2229',
      'bg-layer-2': '#0E252D',
      'bg-layer-3': '#112C34',
      'bg-overlay': '#14110D',
      'label-primary': '#E9FCFF',
      'label-secondary': '#AEDBE2',
      'label-tertiary': '#8EC0C8',
      'label-dimmed': '#6FA5AF',
      'border-l1': '#16333C',
      'border-l2': '#1A3B45',
      'border-l3': '#1F4550',
      'brand-primary': '#37D7E4',
      'brand-primary-invert': '#04222a',
      'brand-text': '#04222a',
      'button-primary-fill': '#37D7E4',
      'button-primary-hover': '#4FDCE7',
      'button-primary-dimmed': '#0D434B',
      'interactive-bg-hover': '#0C2229',
      'interactive-bg-active': '#0B2128',
      'markdown-code-block': '#0B2128',
      'markdown-inline-code': '#0C2229',
      'scrollbar-bg-l1': '#183841',
      'scrollbar-hover-l1': '#1F4550',
      'bg-module-platform': '#0E252D',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#E3F4F6',
      'sidebar-nav-item-active-accent': '#007C92',
      'sidebar-nav-item-active': '#D9EFF2',
      'sidebar-nav-item-hover': '#E4F5F7',
      'menu': '#FAFEFE',
      'bubble': '#EDF9FA',
      'bubble-highlight': '#D9EFF2',
      },
      dark: {
      'sidebar-fill': '#0B2128',
      'sidebar-nav-item-active-accent': '#37D7E4',
      'sidebar-nav-item-active': '#0D434B',
      'sidebar-nav-item-hover': '#0C2229',
      'menu': '#112C34',
      'bubble': '#0E262E',
      'bubble-highlight': '#0C3D46',
      },
    },
  },
  {
    id: 'rx-fortune-forge',
    name: '熔炉金红（Fortune Forge）',
    description: 'Reasonix 官方 Fortune Forge——锻炉金红，炽热专注',
    light: {
      'bg-base': '#FFFBF1',
      'bg-layer-1': '#F9EFD5',
      'bg-layer-2': '#FAF1DC',
      'bg-layer-3': '#FFFDF6',
      'bg-overlay': '#FFFDF6',
      'label-primary': '#382116',
      'label-secondary': '#6E4E35',
      'label-tertiary': '#8C6C4E',
      'label-dimmed': '#9D8061',
      'border-l1': '#F2E7CD',
      'border-l2': '#E5D2A9',
      'border-l3': '#D6B87E',
      'brand-primary': '#A92D22',
      'brand-primary-invert': '#FFF8E8',
      'brand-text': '#FFF8E8',
      'button-primary-fill': '#95281E',
      'button-primary-hover': '#84231B',
      'button-primary-dimmed': '#F6E4D4',
      'interactive-bg-hover': '#F9EED4',
      'interactive-bg-active': '#F8EED4',
      'markdown-code-block': '#FCF5E3',
      'markdown-inline-code': '#F9EFD5',
      'scrollbar-bg-l1': '#EBDBB9',
      'scrollbar-hover-l1': '#D6B87E',
      'bg-module-platform': '#FAF1DC',
      'tooltip-bg': '#382116',
      'toast-bg': '#382116',
    },
    dark: {
      'bg-base': '#231A11',
      'bg-layer-1': '#271C12',
      'bg-layer-2': '#291E13',
      'bg-layer-3': '#302417',
      'bg-overlay': '#14110D',
      'label-primary': '#FFF2D1',
      'label-secondary': '#DDC49C',
      'label-tertiary': '#C3AB84',
      'label-dimmed': '#A9926B',
      'border-l1': '#3B2C1A',
      'border-l2': '#43321E',
      'border-l3': '#4D3A22',
      'brand-primary': '#E8AD38',
      'brand-primary-invert': '#241606',
      'brand-text': '#241606',
      'button-primary-fill': '#E8AD38',
      'button-primary-hover': '#EBB750',
      'button-primary-dimmed': '#47310F',
      'interactive-bg-hover': '#261C12',
      'interactive-bg-active': '#261B11',
      'markdown-code-block': '#251B12',
      'markdown-inline-code': '#271C12',
      'scrollbar-bg-l1': '#40301C',
      'scrollbar-hover-l1': '#4D3A22',
      'bg-module-platform': '#291E13',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#F8EDD3',
      'sidebar-nav-item-active-accent': '#A92D22',
      'sidebar-nav-item-active': '#F6E4D4',
      'sidebar-nav-item-hover': '#F9EED4',
      'menu': '#FFFDF6',
      'bubble': '#FCF5E3',
      'bubble-highlight': '#F6E4D4',
      },
      dark: {
      'sidebar-fill': '#251B11',
      'sidebar-nav-item-active-accent': '#E8AD38',
      'sidebar-nav-item-active': '#47310F',
      'sidebar-nav-item-hover': '#261C12',
      'menu': '#302417',
      'bubble': '#2A1F14',
      'bubble-highlight': '#412D0E',
      },
    },
  },
  {
    id: 'rx-rose-dawn',
    name: '玫瑰晨光（Rose Dawn）',
    description: 'Reasonix 官方 Rose Dawn——玫瑰晨雾，柔和温暖',
    light: {
      'bg-base': '#FFFCFC',
      'bg-layer-1': '#FBEFF1',
      'bg-layer-2': '#FDF3F4',
      'bg-layer-3': '#FFFFFF',
      'bg-overlay': '#FFFFFF',
      'label-primary': '#3A252C',
      'label-secondary': '#6D4A55',
      'label-tertiary': '#8B626E',
      'label-dimmed': '#A97B87',
      'border-l1': '#F5E3E7',
      'border-l2': '#ECD1D8',
      'border-l3': '#E2BCC6',
      'brand-primary': '#B43F65',
      'brand-primary-invert': '#FFF7F8',
      'brand-text': '#FFF7F8',
      'button-primary-fill': '#9E3759',
      'button-primary-hover': '#8C314F',
      'button-primary-dimmed': '#F8E5E9',
      'interactive-bg-hover': '#FBEEF0',
      'interactive-bg-active': '#FBEDF0',
      'markdown-code-block': '#FDF6F6',
      'markdown-inline-code': '#FBEFF1',
      'scrollbar-bg-l1': '#F0D9DF',
      'scrollbar-hover-l1': '#E2BCC6',
      'bg-module-platform': '#FDF3F4',
      'tooltip-bg': '#3A252C',
      'toast-bg': '#3A252C',
    },
    dark: {
      'bg-base': '#231820',
      'bg-layer-1': '#281B21',
      'bg-layer-2': '#2A1D24',
      'bg-layer-3': '#312329',
      'bg-overlay': '#14110D',
      'label-primary': '#FFF3F6',
      'label-secondary': '#D9B3C0',
      'label-tertiary': '#C098A6',
      'label-dimmed': '#A87C8C',
      'border-l1': '#3A2832',
      'border-l2': '#422D38',
      'border-l3': '#4C3440',
      'brand-primary': '#E26D91',
      'brand-primary-invert': '#2A121D',
      'brand-text': '#2A121D',
      'button-primary-fill': '#E26D91',
      'button-primary-hover': '#E57F9E',
      'button-primary-dimmed': '#4B2232',
      'interactive-bg-hover': '#271A21',
      'interactive-bg-active': '#261A22',
      'markdown-code-block': '#261A20',
      'markdown-inline-code': '#281B21',
      'scrollbar-bg-l1': '#3E2B36',
      'scrollbar-hover-l1': '#4C3440',
      'bg-module-platform': '#2A1D24',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#FBECEF',
      'sidebar-nav-item-active-accent': '#B43F65',
      'sidebar-nav-item-active': '#F8E5E9',
      'sidebar-nav-item-hover': '#FBEEF0',
      'menu': '#FFFFFF',
      'bubble': '#FDF6F6',
      'bubble-highlight': '#F8E5E9',
      },
      dark: {
      'sidebar-fill': '#251922',
      'sidebar-nav-item-active-accent': '#E26D91',
      'sidebar-nav-item-active': '#4B2232',
      'sidebar-nav-item-hover': '#271A21',
      'menu': '#312329',
      'bubble': '#2A1E24',
      'bubble-highlight': '#46202E',
      },
    },
  },
  {
    id: 'rx-sage-breeze',
    name: '鼠尾草微风（Sage Breeze）',
    description: 'Reasonix 官方 Sage Breeze——鼠尾草绿，自然清新',
    light: {
      'bg-base': '#FAFAF4',
      'bg-layer-1': '#EFEFE2',
      'bg-layer-2': '#F1F1E5',
      'bg-layer-3': '#FCFCF6',
      'bg-overlay': '#FCFCF6',
      'label-primary': '#26332D',
      'label-secondary': '#4E6157',
      'label-tertiary': '#65786D',
      'label-dimmed': '#73857A',
      'border-l1': '#E8E8D8',
      'border-l2': '#D6D6BA',
      'border-l3': '#BFC095',
      'brand-primary': '#47735F',
      'brand-primary-invert': '#F7F7EF',
      'brand-text': '#F7F7EF',
      'button-primary-fill': '#3E6554',
      'button-primary-hover': '#375A4A',
      'button-primary-dimmed': '#E5EAE1',
      'interactive-bg-hover': '#EFEFE1',
      'interactive-bg-active': '#EEEEE1',
      'markdown-code-block': '#F4F4EB',
      'markdown-inline-code': '#EFEFE2',
      'scrollbar-bg-l1': '#DEDEC7',
      'scrollbar-hover-l1': '#BFC095',
      'bg-module-platform': '#F1F1E5',
      'tooltip-bg': '#26332D',
      'toast-bg': '#26332D',
    },
    dark: {
      'bg-base': '#151E19',
      'bg-layer-1': '#17211C',
      'bg-layer-2': '#19231D',
      'bg-layer-3': '#1E2922',
      'bg-overlay': '#14110D',
      'label-primary': '#EEF6F0',
      'label-secondary': '#B7CDBF',
      'label-tertiary': '#9AB2A4',
      'label-dimmed': '#7E968A',
      'border-l1': '#25322B',
      'border-l2': '#2B3A32',
      'border-l3': '#32443A',
      'brand-primary': '#84CBA7',
      'brand-primary-invert': '#0E1A13',
      'brand-text': '#0E1A13',
      'button-primary-fill': '#84CBA7',
      'button-primary-hover': '#93D1B2',
      'button-primary-dimmed': '#233A2E',
      'interactive-bg-hover': '#17201B',
      'interactive-bg-active': '#16201B',
      'markdown-code-block': '#16201A',
      'markdown-inline-code': '#17211C',
      'scrollbar-bg-l1': '#28362F',
      'scrollbar-hover-l1': '#32443A',
      'bg-module-platform': '#19231D',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#EEEEE0',
      'sidebar-nav-item-active-accent': '#47735F',
      'sidebar-nav-item-active': '#E5EAE1',
      'sidebar-nav-item-hover': '#EFEFE1',
      'menu': '#FCFCF6',
      'bubble': '#F4F4EB',
      'bubble-highlight': '#E5EAE1',
      },
      dark: {
      'sidebar-fill': '#161F1A',
      'sidebar-nav-item-active-accent': '#84CBA7',
      'sidebar-nav-item-active': '#233A2E',
      'sidebar-nav-item-hover': '#17201B',
      'menu': '#1E2922',
      'bubble': '#1A241E',
      'bubble-highlight': '#203529',
      },
    },
  },
  {
    id: 'rx-spark-notebook',
    name: '火花笔记（Spark Notebook）',
    description: 'Reasonix 官方 Spark Notebook——青瓷墨黑，专注书写',
    light: {
      'bg-base': '#FFFCF4',
      'bg-layer-1': '#F9F1DE',
      'bg-layer-2': '#FAF3E2',
      'bg-layer-3': '#FFFDF7',
      'bg-overlay': '#FFFDF7',
      'label-primary': '#2B2F35',
      'label-secondary': '#565D66',
      'label-tertiary': '#6D757F',
      'label-dimmed': '#7B838D',
      'border-l1': '#F2E9D4',
      'border-l2': '#E4D5B4',
      'border-l3': '#D2BC8E',
      'brand-primary': '#007B78',
      'brand-primary-invert': '#F3FBFA',
      'brand-text': '#F3FBFA',
      'button-primary-fill': '#006C6A',
      'button-primary-hover': '#00605E',
      'button-primary-dimmed': '#DBEEED',
      'interactive-bg-hover': '#F9F1DD',
      'interactive-bg-active': '#F8F0DD',
      'markdown-code-block': '#FCF6E9',
      'markdown-inline-code': '#F9F1DE',
      'scrollbar-bg-l1': '#EADEC2',
      'scrollbar-hover-l1': '#D2BC8E',
      'bg-module-platform': '#FAF3E2',
      'tooltip-bg': '#2B2F35',
      'toast-bg': '#2B2F35',
    },
    dark: {
      'bg-base': '#191D21',
      'bg-layer-1': '#1B1F23',
      'bg-layer-2': '#1D2226',
      'bg-layer-3': '#23282D',
      'bg-overlay': '#14110D',
      'label-primary': '#F8F5E9',
      'label-secondary': '#C9CCBF',
      'label-tertiary': '#AAAEA4',
      'label-dimmed': '#8B918A',
      'border-l1': '#2A3138',
      'border-l2': '#303840',
      'border-l3': '#38404A',
      'brand-primary': '#42D1C6',
      'brand-primary-invert': '#08201E',
      'brand-text': '#08201E',
      'button-primary-fill': '#42D1C6',
      'button-primary-hover': '#59D7CD',
      'button-primary-dimmed': '#12403C',
      'interactive-bg-hover': '#1B1F23',
      'interactive-bg-active': '#1A1E22',
      'markdown-code-block': '#1A1E22',
      'markdown-inline-code': '#1B1F23',
      'scrollbar-bg-l1': '#2E353C',
      'scrollbar-hover-l1': '#38404A',
      'bg-module-platform': '#1D2226',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#F8F0DC',
      'sidebar-nav-item-active-accent': '#007B78',
      'sidebar-nav-item-active': '#DBEEED',
      'sidebar-nav-item-hover': '#F9F1DD',
      'menu': '#FFFDF7',
      'bubble': '#FCF6E9',
      'bubble-highlight': '#DBEEED',
      },
      dark: {
      'sidebar-fill': '#1A1E22',
      'sidebar-nav-item-active-accent': '#42D1C6',
      'sidebar-nav-item-active': '#12403C',
      'sidebar-nav-item-hover': '#1B1F23',
      'menu': '#23282D',
      'bubble': '#1E2227',
      'bubble-highlight': '#113B37',
      },
    },
  },
  {
    id: 'rx-violet-starlight',
    name: '紫罗兰星光（Violet Starlight）',
    description: 'Reasonix 官方 Violet Starlight——星辉紫韵，沉静深邃',
    light: {
      'bg-base': '#FAF8FF',
      'bg-layer-1': '#EFEBFB',
      'bg-layer-2': '#F1EDFB',
      'bg-layer-3': '#FCFAFF',
      'bg-overlay': '#FCFAFF',
      'label-primary': '#251F3C',
      'label-secondary': '#544B74',
      'label-tertiary': '#726A94',
      'label-dimmed': '#877EA6',
      'border-l1': '#E8E3F7',
      'border-l2': '#DAD2F2',
      'border-l3': '#CABDEC',
      'brand-primary': '#6242C7',
      'brand-primary-invert': '#F7F4FF',
      'brand-text': '#F7F4FF',
      'button-primary-fill': '#563AAF',
      'button-primary-hover': '#4C339B',
      'button-primary-dimmed': '#E8E2F9',
      'interactive-bg-hover': '#EFEAFB',
      'interactive-bg-active': '#EEEAFA',
      'markdown-code-block': '#F4F2FD',
      'markdown-inline-code': '#EFEBFB',
      'scrollbar-bg-l1': '#E0DAF4',
      'scrollbar-hover-l1': '#CABDEC',
      'bg-module-platform': '#F1EDFB',
      'tooltip-bg': '#251F3C',
      'toast-bg': '#251F3C',
    },
    dark: {
      'bg-base': '#111630',
      'bg-layer-1': '#131834',
      'bg-layer-2': '#151B36',
      'bg-layer-3': '#1A2140',
      'bg-overlay': '#14110D',
      'label-primary': '#F4F2FF',
      'label-secondary': '#C2BDE8',
      'label-tertiary': '#A49ED0',
      'label-dimmed': '#8580B8',
      'border-l1': '#222B4E',
      'border-l2': '#273259',
      'border-l3': '#2E3A66',
      'brand-primary': '#9B86FF',
      'brand-primary-invert': '#14102E',
      'brand-text': '#14102E',
      'button-primary-fill': '#9B86FF',
      'button-primary-hover': '#A795FF',
      'button-primary-dimmed': '#2C2554',
      'interactive-bg-hover': '#131833',
      'interactive-bg-active': '#121733',
      'markdown-code-block': '#121732',
      'markdown-inline-code': '#131834',
      'scrollbar-bg-l1': '#252F54',
      'scrollbar-hover-l1': '#2E3A66',
      'bg-module-platform': '#151B36',
      'tooltip-bg': '#241F16',
      'toast-bg': '#241F16',
    },
    specific: {
      light: {
      'sidebar-fill': '#EEE9FA',
      'sidebar-nav-item-active-accent': '#6242C7',
      'sidebar-nav-item-active': '#E8E2F9',
      'sidebar-nav-item-hover': '#EFEAFB',
      'menu': '#FCFAFF',
      'bubble': '#F4F2FD',
      'bubble-highlight': '#E8E2F9',
      },
      dark: {
      'sidebar-fill': '#121732',
      'sidebar-nav-item-active-accent': '#9B86FF',
      'sidebar-nav-item-active': '#2C2554',
      'sidebar-nav-item-hover': '#131833',
      'menu': '#1A2140',
      'bubble': '#161C38',
      'bubble-highlight': '#28224D',
      },
    },
  },
  {
    id: 'oc-classic',
    name: 'opencode 经典（opencode Classic）',
    description: 'opencode 官方配方——近黑/近白中性底 + 鲜橙强调（#FF8C00 系）',
    light: {
      'bg-base': '#FCFCFD',
      'bg-layer-1': '#F6F6F7',
      'bg-layer-2': '#F6F6F7',
      'bg-layer-3': '#EFEFF0',
      'bg-overlay': '#EFEFF0',
      'label-primary': '#141517',
      'label-secondary': '#55595F',
      'label-tertiary': '#70747A',
      'label-dimmed': '#81868B',
      'border-l1': '#E7E7E9',
      'border-l2': '#DADADD',
      'border-l3': '#C9CBCF',
      'brand-primary': '#C25E02',
      'brand-primary-invert': '#FFF7ED',
      'brand-text': '#FFF7ED',
      'button-primary-fill': '#AB5302',
      'button-primary-hover': '#974902',
      'button-primary-dimmed': '#F9E8D6',
      'interactive-bg-hover': '#F4F4F5',
      'interactive-bg-active': '#F3F3F4',
      'markdown-code-block': '#F9F9FA',
      'markdown-inline-code': '#F6F6F7',
      'scrollbar-bg-l1': '#E0E0E2',
      'scrollbar-hover-l1': '#C9CBCF',
      'bg-module-platform': '#EFEFF0',
      'tooltip-bg': '#141517',
      'toast-bg': '#141517',
    },
    dark: {
      'bg-base': '#0B0C0E',
      'bg-layer-1': '#131518',
      'bg-layer-2': '#191C1F',
      'bg-layer-3': '#212529',
      'bg-overlay': '#131518',
      'label-primary': '#F0F2F5',
      'label-secondary': '#A8AEB5',
      'label-tertiary': '#8B9198',
      'label-dimmed': '#6E747B',
      'border-l1': '#24272B',
      'border-l2': '#2E3237',
      'border-l3': '#3A4046',
      'brand-primary': '#FF8C00',
      'brand-primary-invert': '#1A0F02',
      'brand-text': '#1A0F02',
      'button-primary-fill': '#FF8C00',
      'button-primary-hover': '#FF9A1F',
      'button-primary-dimmed': '#432602',
      'interactive-bg-hover': '#121416',
      'interactive-bg-active': '#111315',
      'markdown-code-block': '#0F1013',
      'markdown-inline-code': '#131518',
      'scrollbar-bg-l1': '#2A2D32',
      'scrollbar-hover-l1': '#3A4046',
      'bg-module-platform': '#191C1F',
      'tooltip-bg': '#212529',
      'toast-bg': '#212529',
    },
    specific: {
      light: {
      'sidebar-fill': '#F1F1F2',
      'sidebar-nav-item-active-accent': '#C25E02',
      'sidebar-nav-item-active': '#F9E8D6',
      'sidebar-nav-item-hover': '#F4F4F5',
      'menu': '#EFEFF0',
      'bubble': '#F9F9FA',
      'bubble-highlight': '#F9E8D6',
      },
      dark: {
      'sidebar-fill': '#0F1113',
      'sidebar-nav-item-active-accent': '#FF8C00',
      'sidebar-nav-item-active': '#432602',
      'sidebar-nav-item-hover': '#121416',
      'menu': '#212529',
      'bubble': '#16181C',
      'bubble-highlight': '#3C2202',
      },
    },
  },
  {
    id: 'oc-graphite',
    name: 'opencode 石墨（opencode Graphite）',
    description: 'opencode 石墨变体——暖灰中性底 + 炽橙强调（#E8590C 系）',
    light: {
      'bg-base': '#F8F8F6',
      'bg-layer-1': '#F1F1EE',
      'bg-layer-2': '#F1F1EE',
      'bg-layer-3': '#EAEAE6',
      'bg-overlay': '#EAEAE6',
      'label-primary': '#1B1B1A',
      'label-secondary': '#5D5D5A',
      'label-tertiary': '#767673',
      'label-dimmed': '#868682',
      'border-l1': '#E2E2DE',
      'border-l2': '#D4D4D0',
      'border-l3': '#C4C4C0',
      'brand-primary': '#C24E02',
      'brand-primary-invert': '#FFF6EC',
      'brand-text': '#FFF6EC',
      'button-primary-fill': '#AB4502',
      'button-primary-hover': '#973D02',
      'button-primary-dimmed': '#F9E5D5',
      'interactive-bg-hover': '#EFEFEC',
      'interactive-bg-active': '#EEEEEA',
      'markdown-code-block': '#F4F4F2',
      'markdown-inline-code': '#F1F1EE',
      'scrollbar-bg-l1': '#DADAD6',
      'scrollbar-hover-l1': '#C4C4C0',
      'bg-module-platform': '#EAEAE6',
      'tooltip-bg': '#1B1B1A',
      'toast-bg': '#1B1B1A',
    },
    dark: {
      'bg-base': '#101214',
      'bg-layer-1': '#17191C',
      'bg-layer-2': '#1D2023',
      'bg-layer-3': '#25282C',
      'bg-overlay': '#17191C',
      'label-primary': '#E9ECEF',
      'label-secondary': '#9AA0A6',
      'label-tertiary': '#7E848A',
      'label-dimmed': '#5C6166',
      'border-l1': '#26292D',
      'border-l2': '#303439',
      'border-l3': '#3D4147',
      'brand-primary': '#E8590C',
      'brand-primary-invert': '#160A02',
      'brand-text': '#160A02',
      'button-primary-fill': '#E8590C',
      'button-primary-hover': '#EB6D29',
      'button-primary-dimmed': '#3C1804',
      'interactive-bg-hover': '#15171A',
      'interactive-bg-active': '#141618',
      'markdown-code-block': '#141618',
      'markdown-inline-code': '#17191C',
      'scrollbar-bg-l1': '#2C2F34',
      'scrollbar-hover-l1': '#3D4147',
      'bg-module-platform': '#1D2023',
      'tooltip-bg': '#25282C',
      'toast-bg': '#25282C',
    },
    specific: {
      light: {
      'sidebar-fill': '#ECECE8',
      'sidebar-nav-item-active-accent': '#C24E02',
      'sidebar-nav-item-active': '#F9E5D5',
      'sidebar-nav-item-hover': '#EFEFEC',
      'menu': '#EAEAE6',
      'bubble': '#F4F4F2',
      'bubble-highlight': '#F9E5D5',
      },
      dark: {
      'sidebar-fill': '#121416',
      'sidebar-nav-item-active-accent': '#E8590C',
      'sidebar-nav-item-active': '#3C1804',
      'sidebar-nav-item-hover': '#15171A',
      'menu': '#25282C',
      'bubble': '#1A1D20',
      'bubble-highlight': '#361604',
      },
    },
  },
]

/** Sentinel id meaning "no override / native look". */
export const DEFAULT_SKIN_ID = 'default'

/** Find a skin by id (undefined for unknown or `default`). */
export function findSkin(id: string): DshSkin | undefined {
  if (id === DEFAULT_SKIN_ID) return undefined
  return SKINS.find((skin) => skin.id === id)
}

/** Class toggled briefly around a skin swap so token-driven surfaces animate. */
const SKIN_SWITCH_CLASS = 'mg-skin-switching'
/**
 * One-shot global color transition while a skin swap settles (~150ms). Injected
 * with the stylesheet so BOTH skin→skin and →default swaps animate the
 * token-driven surfaces without enumerating elements; stationary afterwards
 * (the rules only apply while the class is present).
 */
const SKIN_SWITCH_CSS = `body.${SKIN_SWITCH_CLASS},body.${SKIN_SWITCH_CLASS} *{` +
  'transition:background-color .15s ease,color .15s ease,border-color .15s ease,fill .15s ease!important}'

/** Add the switch class, remove it once the transition has settled. */
function flashSkinSwitch(): void {
  document.body.classList.add(SKIN_SWITCH_CLASS)
  window.setTimeout(() => document.body.classList.remove(SKIN_SWITCH_CLASS), 180)
}

/**
 * Apply (or clear) a skin by injecting/updating one `<style id="mg-dsh-skin">`
 * element in the document head. Removing is a no-op when nothing was injected.
 */
export function applySkin(skinId: string): void {
  let style = document.getElementById('mg-dsh-skin') as HTMLStyleElement | null
  if (style === null) {
    style = document.createElement('style')
    style.id = 'mg-dsh-skin'
    document.head.appendChild(style)
  }
  const skin = findSkin(skinId)
  style.textContent = SKIN_SWITCH_CSS + (skin === undefined ? '' : buildCss(skin))
  flashSkinSwitch()
}

/** True once the user explicitly picked a skin in this page lifetime. The
 * boot skin restore must not clobber a user pick that raced it (B8). */
let userPickedSkin = false

/** Mark that the user explicitly picked a skin (settings card onPickSkin). */
export function markSkinUserPicked(): void {
  userPickedSkin = true
}

/** Whether the user already picked a skin in this page lifetime. */
export function hasUserPickedSkin(): boolean {
  return userPickedSkin
}

/** Read the persisted skin id through the plugin's config API. */
export async function fetchStoredSkin(): Promise<string> {
  try {
    const res = await fetch('/api/dsh-hub/config')
    if (!res.ok) return DEFAULT_SKIN_ID
    const body = (await res.json()) as { ok?: boolean; value?: { skin?: string } }
    const skin = body.ok === true ? body.value?.skin : undefined
    return typeof skin === 'string' && skin !== '' ? skin : DEFAULT_SKIN_ID
  } catch {
    return DEFAULT_SKIN_ID
  }
}
